# Generated by Django 4.2.7 on 2023-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('myImage', models.FileField(default=None, max_length=250, null=True, upload_to='mainpage/')),
            ],
        ),
    ]
