# Generated by Django 4.2.7 on 2023-11-23 17:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
