# Generated by Django 4.2.7 on 2023-11-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('dashboard', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
