# Generated by Django 4.2.7 on 2023-11-23 17:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='myImage',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='works/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='dashboard',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='time',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
